language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ewrHaGMih8fseMgaFCrbMlwbu9x57ZqViiMacLftTHPg/mfOjmQKOCEbfh5mMs4tfVDC5Lja6ay5bX/lpbl7vIeVqpzg1UMsGyADL4Zbmfb785fgo1a+WZnLViyDbHP7FnnhPQC0JFY29XrS3GxCZfE60odCCmB4HL8oAFiWVs0gXE1BD1M+3LdQKHbJYgHPY8BrjXtASz/NkqzCyxbdDgbgR/i27sbTSk7ri4glhcC5V8bME5N5HK6wNftuZT5VslEUs+nQvQsDOD3uhYkKKlegoLmcuGFRzOjaWp9REi4rYpRjZegH/isNusVphWnU9MUSUIhXyWVTebcED3ut4BWfxZNxN5yqmt2fXR+uCgXDNcIpgK5aQZKfoJ5r6BM7Ysp/TV0i3hbcW0Czhk+1eBzz+eu3TEozOsTJGIOrQbiNZ3UXJfu/1CwsdGEZ1eVMDJHJSDe7FZtxjUx8Qro/x4iV7TXGstjPqoBwoHOegcEAdPxB3vmCPq5mI/dZF+YdQ2hEUG4gRzOo8Qxxfy+Eo+iOr5xhvH19hK69IWWAVbWmTE6wXa0maEYRgrp557pkdDiSfJI3J4ncdRIOzaiVqhdXyeDtje6pXxSCD6HQK2JmeyH+cOkU0PO5bod8BS8Mi9vkezmiwCFJb1lqD0TybjHt1MHtg2kWFwUxdS1RJ5U=
  app: language-avi-saule
  on:
    repo: Avizc/learn-danish
